apiVersion: v1
kind: Secret
metadata:
    name: my-secret
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:3NYxb8xbdieee6Wo,iv:AT6n+b+2oKOKOg2DBshm5Z0IiztO511XRVJtS8pa58A=,tag:5+X11ia90I3lFoPyhW8plQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOEdpQzJmRmVvVjBxRjgv
            T0grTU9aUUU3REViQXpuMGNqNXNGc0M1UnhjCnkySEF5M2YzN1dMOEcvYmxoems0
            ZGlJM3FNd0lsc2o2WjJZcUtUd2tiNzgKLS0tIHlHMEFDSGt2QlV3NW9oREpocGxw
            d3BnTWdYVURZS1U0eGdrNFRxTHVJdkkKTm1OjcxZnsPHjEEI0YaNJAlPUOXXFw28
            9OVGU7mb/9kJB87rvb3N9NEMWaosHI7IWdq1Pdr5Ko3FqPvCYt727g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age169mnf2y4tuj63ggmq6y60h9mkgw7cuml9kwxazeqwcv0hygfzu2qgs4zcx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T12:33:45Z"
    mac: ENC[AES256_GCM,data:dNlB+/Hmw6LIR6WduurpW77qax4OAT2kNJEhYkxyl3XKrk3iIpcF/dnDZq+VBJsv54W1AopUtc0QbBqd1SC14x9elpfexi9ifBdlo+cQxEpQ/jnh8ftcE/exKb4mDAOT18RJPkIOEDB+CGvTssQDlKLPt1GVnFtz1h8hTgor4VA=,iv:pCkFzILL4vCy5KpoKozqskhC3pCNW2i7NdVyoueKjic=,tag:snt+qbGw6tPuAXjOYdsJFQ==,type:str]
    version: 3.13.3
