apiVersion: v1
kind: Secret
metadata:
    name: hello
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:ADZnFbdHxPXR45o3,iv:D/VjMMpFuJb83p7VOgzyECx00K2t2g/G/zJw51M98Yg=,tag:IwsCByzryo+3zAiK751LXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQlZoaEM1UEROWVhlTito
            dklVaWw1R1U0WWV6eExRTHRJcGQwRjFvYWxJClhiNmVpM3BtWERpMzRTRmJJaXpQ
            ZmZpNzhObXl4cTlTYjlNVnVrUTh3aFEKLS0tIGQzTk1xWGE3RDdUUXZ6VFR5bUhx
            WkppalE1MjV6YWtuVEZhS0JOR0pJTkUKLnuw/QzPow63+ynypvY0fqAOfO30tB5l
            QR7cVo8x6TmuDAo5CRiDfTGhwkoZedZpVhg9Ijt6yAGkUofd7u3ySA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age169mnf2y4tuj63ggmq6y60h9mkgw7cuml9kwxazeqwcv0hygfzu2qgs4zcx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T22:49:13Z"
    mac: ENC[AES256_GCM,data:YvAseqbua9Nw/sO4QUoz/3jrbSp1DAKWbGB5KJrcSMepTqFcgF5xaCnv5yMoneH7LR4plfJew1Lv4IlBPIoJaN6/qNdrRK7dr8S8m/T8YKJrcn531+TeJSfnoGBtCpVurKrxio9/DPFTCXY174P7PE5lIkC4NelYWs5Df301p4w=,iv:6GTvcx+VOW4BgBNhhdw0Z9yZMgLXTuqOc7beRy+p+Bs=,tag:hEH1uLBAyHq4huB+udkrSg==,type:str]
    version: 3.13.3
