apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: my-route
spec:
  parentRefs:
    - name: my-gateway
  rules:
    - backendRefs:
        # The *Service* port (80), not the container's (8000)
        - name: my-service
          port: 80
      # matches:
      #   - path:
      #       type: PathPrefix
      #       value: /
