FROM docker.io/library/python:3.14-slim

WORKDIR /app
RUN pip install --no-cache-dir "fastapi[standard]"
COPY main.py .

EXPOSE 8000
CMD ["fastapi", "run", "main.py", "--host", "0.0.0.0", "--port", "8000"]
