FROM docker.io/library/debian:stable-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends dnsmasq \
 && rm -rf /var/lib/apt/lists/*

EXPOSE 53/udp
EXPOSE 53/tcp

ENTRYPOINT ["dnsmasq"]
CMD ["--no-daemon"]
