# Fichier de configuration minimaliste pour dnsmasq

# Ne pas lire /etc/resolv.conf ni /etc/hosts du système hôte
no-resolv
no-hosts

# Enregistrements DNS statiques
address=/foo.jdhp.org/192.168.0.1
address=/bar.jdhp.org/192.168.0.2

# Logs
log-queries
