#!/bin/sh

# Hello Java
# Copyright (c) 2012 Jérémie DECOCK <jd.jdhp@gmail.com>

ROOT="."
JVM_ARGS="$@"
PROGRAM_ARGS=
LIBS="${ROOT}/bin/"

#java ${JVM_ARGS} -jar ${ROOT}/hello.jar ${PROGRAM_ARGS}
java ${JVM_ARGS} -cp ${LIBS} org.jdhp.snippets.Hello ${PROGRAM_ARGS}
