image: quay.io/jupyter/scipy-notebook
#image: python:3.8-slim

# variables:
#   GIT_SUBMODULE_STRATEGY: recursive

# before_script:
# - apt update -q -y
# - apt-get install -y build-essential unzip
# - export PIP_CACHE_DIR="/opt/cache/pip"
# - python3 -m pip install -r requirements-build.txt
# - python3 -m pip install .

# test:
#   stage: test
#   script:
#   - pytest

pages:
  stage: deploy
  script:
  - mkdir -p public/notebooks/pandas
  - mv index.html public/
  #- jupyter nbconvert --to html --template='jdhp_html_fr.tpl' --execute python/pandas/*.ipynb && mv python/pandas/*.html public/notebooks/pandas/
  - jupyter nbconvert --to html --execute python/pandas/*.ipynb && mv python/pandas/*.html public/notebooks/pandas/
  #- sphinx-build -b html docs/ build/sphinx/html/
  #- mv build/sphinx/html/ public/
  #- coverage run -m pytest
  #- coverage html
  #- mv htmlcov public/
  artifacts:
    paths:
    - public
  only:
  - master

