#!/bin/sh

# Hello
# Copyright (c) 2012 Jérémie DECOCK <jd.jdhp@gmail.com>

ROOT="."
JVM_ARGS=
PROGRAM_ARGS="$@"
LIBS="${ROOT}/bin/:${ROOT}/ext/lib/commons-cli/commons-cli-1.2.jar"

#java ${JVM_ARGS} -jar ${ROOT}/hello_commons_cli.jar ${PROGRAM_ARGS}
java ${JVM_ARGS} -cp ${LIBS} org.jdhp.snippets.commons.HelloCommonsCli ${PROGRAM_ARGS}
