#!/usr/bin/env ansible-playbook

# https://docs.docker.com/compose/gettingstarted/

---
- name: Install and configure a (production ready) FastAPI server using Docker Compose
  hosts: webservers
  become: True

  vars:
    src_application_path: "{{ playbook_dir }}/../"
    dst_application_path: /srv/hello

  tasks:

    - name: Install Debian packages (Docker and rsync)
      apt:
        name:
          - docker.io
          - python3-docker
          - docker-compose
          - rsync
        update_cache: yes

    - name: Ensures the directory that will contain the app exists
      file:
        path: "{{ dst_application_path }}"
        state: directory
        recurse: yes

    - name: Sync the App
      synchronize:
        src: "{{ src_application_path }}"
        dest: "{{ dst_application_path }}"
        delete: yes
        mode: push
        rsync_opts:
          - "--exclude=.git/"
          - "--exclude=env/"
          - "--exclude=ansible_playbooks/"
          - "--exclude=*.egg-info/"
          - "--exclude=.vscode/"
          - "--exclude=__pycache__/"
          - "--exclude=*.pyc"
          - "--exclude=*.pyo"
          - "--exclude=*.pyd"
          - "--exclude=.gitlab-ci.yml"
          - "--exclude=.gitignore"

    # Use files parameter to use multiple docker-compose.yml files
    - name: Deploy the App with Docker Compose
      docker_compose:
        project_src: "{{ dst_application_path }}"
        files:
          - docker-compose.yml
        state: present
        build: yes
