version: '3'
services:
  couchdb:
    image: couchdb:3.3.3

    container_name: couchdb-server

    #restart: unless-stopped

    environment:
      COUCHDB_USER: ${COUCHDB_JDHP_SNIPPETS_USER}
      COUCHDB_PASSWORD: ${COUCHDB_JDHP_SNIPPETS_PASSWORD}

    ports:
      - "5984:5984"

    volumes:
      - couchdb-data:/opt/couchdb/data

volumes:
  couchdb-data:
