apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - image: docker.io/your-username/hello-fastapi:1.0
          name: hello
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
