apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
    - image: ghcr.io/jeremiedecock/hello-fastapi:1.0
      name: hello
      imagePullPolicy: Always
  imagePullSecrets:
    - name: ghcr-secret
