version: "3.4"
services:
  wsgi:
    container_name: wsgi
    build: ./wsgi
    # https://stackoverflow.com/questions/38346847/nginx-docker-container-502-bad-gateway-response
    network_mode: host
    #ports:
    #  - "8000:8000"
  reverseproxy:
    container_name: reverseproxy
    build: ./reverseproxy
    # https://stackoverflow.com/questions/38346847/nginx-docker-container-502-bad-gateway-response
    network_mode: host
    #ports:
    #  - "80:80"