---
- name: Remove the hello app
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Delete the resources
      kubernetes.core.k8s:
        state: absent
        api_version: "{{ item.api_version }}"
        kind: "{{ item.kind }}"
        name: hello
        namespace: default
      loop:
        - {api_version: apps/v1, kind: Deployment}
        - {api_version: v1, kind: Service}
        - {api_version: v1, kind: Secret}
        - {api_version: v1, kind: ConfigMap}
