---
- name: Remove the app
  hosts: localhost
  gather_facts: false
  vars:
    k8s_namespace: snippet-secret-demo

  tasks:
    - name: Delete the resources
      kubernetes.core.k8s:
        state: absent
        api_version: "{{ item.api_version }}"
        kind: "{{ item.kind }}"
        name: "{{ item.name }}"
        namespace: "{{ k8s_namespace }}"
      loop:
        - {api_version: apps/v1, kind: Deployment, name: my-deployment}
        - {api_version: v1, kind: Service, name: my-service}
        - {api_version: v1, kind: Secret, name: my-secret}
        - {api_version: v1, kind: ConfigMap, name: my-config-map}

    - name: Delete the namespace for the demo
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Namespace
        name: "{{ k8s_namespace }}"
