version: "3.9"

services:


  #############################################################################
  # Backend                                                                   #
  #############################################################################

  backend:

    # The base relative directory for the context and dockerfile options in a `docker-compose.yml` file
    # is the directory where the `docker-compose.yml` file is located, not the directory
    # from which the `docker-compose up` command is executed.
    build:
      context: ../src                            # Relative to the directory that contains the `docker-compose.yml` file
      dockerfile: ../docker/fastapi.dockerfile   # Relative to the context directory

    restart: unless-stopped

    environment:
      - SQLITE_DATABASE_URL=sqlite:////var/lib/heroes/heroes.sqlite

    labels:
      # Enable Traefik for this specific "backend" service
      - traefik.enable=true

      # Define the port inside of the Docker service to use
      - traefik.http.services.app.loadbalancer.server.port=80
      # Make Traefik use this domain in HTTP
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app-http.rule=Host(`hello.jdhp.org`) # TODO: change to your domain

      # Use the traefik-public network (declared below)
      - traefik.docker.network=traefik-public

      # Make Traefik use this domain in HTTPS
      - traefik.http.routers.app-https.entrypoints=https
      - traefik.http.routers.app-https.rule=Host(`hello.jdhp.org`) # TODO: change to your domain
      - traefik.http.routers.app-https.tls=true

      # Use the "le" (Let's Encrypt) resolver
      - traefik.http.routers.app-https.tls.certresolver=le

      # http-redirect middleware will redirect every http request to https
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true

      # Middleware to redirect HTTP to HTTPS
      - traefik.http.routers.app-http.middlewares=https-redirect
      - traefik.http.routers.app-https.middlewares=admin-auth

    volumes:
      # Add a mounted volume for the gradio-webui database (to make it persistent)
      - "${APPLICATION_DATABASE_PATH}:/var/lib/heroes/"
      # # Add a mounted volume for the gradio-webui log files
      # - "${APPLICATION_LOG_PATH}:/var/log/heroes/"

    # # Comment the following two lines should stay commented as ports are managed by Traefik... To test the service without Traefik, use the docker-compose-app.override.yml file !
    # ports:
    #   - "80:80"

    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - traefik-public


  #############################################################################
  # Frontend                                                                  #
  #############################################################################

  nginx:
    
    # The official Nginx docker image
    image: nginx:1.25.4

    restart: unless-stopped

    labels:
      # Enable Traefik for this specific "nginx" service
      - traefik.enable=true

      # Define the port inside of the Docker service to use
      - traefik.http.services.nginx.loadbalancer.server.port=80

      # Make Traefik use this domain in HTTP
      - traefik.http.routers.nginx-http.entrypoints=http
      - traefik.http.routers.nginx-http.rule=Host(`nginx.hello.jdhp.org`) # TODO: change to your domain

      # Use the traefik-public network (declared below)
      - traefik.docker.network=traefik-public

      # Make Traefik use this domain in HTTPS
      - traefik.http.routers.nginx-https.entrypoints=https
      - traefik.http.routers.nginx-https.rule=Host(`nginx.hello.jdhp.org`) # TODO: change to your domain
      - traefik.http.routers.nginx-https.tls=true

      # Use the "le" (Let's Encrypt) resolver
      - traefik.http.routers.nginx-https.tls.certresolver=le

      # Middleware to redirect HTTP to HTTPS
      - traefik.http.routers.nginx-http.middlewares=https-redirect
      - traefik.http.routers.nginx-https.middlewares=admin-auth

    volumes:
    - "../nginx-static-html-directory:/usr/share/nginx/html:ro"
    # - "${APPLICATION_FRONTEND_PATH}:/usr/share/nginx/html:ro"

    # # Comment the following two lines should stay commented as ports are managed by Traefik... To test the service without Traefik, use the docker-compose-app.override.yml file !
    # ports:
    #   - "80:80"

    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - traefik-public


networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that needs to be publicly available via this Traefik
  traefik-public:
    external: true


volumes:
  heroes-database:
  heroes-logs:
