version: "3.9"

services:

  #############################################################################
  # Backend                                                                   #
  #############################################################################

  backend:

    ports:
      - "8000:80"


  #############################################################################
  # Frontend                                                                  #
  #############################################################################

  nginx:

    ports:
      - "8001:80"

