apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    app: hello
spec:
  containers:
    - image: docker.io/library/nginx:stable-alpine-slim
      name: hello
      imagePullPolicy: Always
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
