version: "3.9"

# See https://www.youtube.com/watch?v=7N5O62FjGDc&list=WL&index=6
# docker network create traefik-public
# docker-compose up -d

services:

  # Reverse proxy #############################################################

  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.10

    # restart: always

    ports:
      # Listen on port 80 (HTTP), necessary to redirect to HTTPS
      - "80:80"
      # Listen on port 443 (HTTPS)
      - "443:443"
      # # The Web UI (enabled by --api.insecure=true)
      # - "8080:8080"

    volumes:
      # So that Traefik can listen to the Docker events, read the labels or other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - /var/run/docker.sock:/var/run/docker.sock
      # Mount the volume to store the certificates
      - traefik-public-certificates:/certificates

    # Enables the web UI and tells Traefik to listen to docker
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      # Do not expose all Docker services (e.g. databases), only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Create an entrypoint "http" listening on port 80
      - --entrypoints.http.address=:80
      # Create an entrypoint "https" listening on port 443
      - --entrypoints.https.address=:443
      # Create the certificate resolver "le" for Let's Encrypt, uses the environment variable jd.jdhp@gmail.com
      - --certificatesresolvers.le.acme.email=jd.jdhp@gmail.com
      # Store the Let's Encrypt certificates in the mounted volume
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      # Use the TLS Challenge for Let's Encrypt
      - --certificatesresolvers.le.acme.tlschallenge=true
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      #- --api.insecure=true

    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - traefik-public

volumes:
  # Create a volume to store the certificates, there is a constraint to make sure
  # Traefik is always deployed to the same Docker node withe the same volume containing
  # the HTTPS certificates
  traefik-public-certificates:

networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that needs to be publicly available via this Traefik
  traefik-public:
    external: true
