# C.f.
# - https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/
# - https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/

services:
  grafana:
    image: docker.io/grafana/grafana-oss
    container_name: grafana
    # restart: unless-stopped
    # environment:
    #  - GF_SERVER_ROOT_URL=http://my.grafana.server/
    #  - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    ports:
     - '3000:3000'
    volumes:
     - 'grafana_storage:/var/lib/grafana'
volumes:
  grafana_storage: {}
