apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - image: docker.io/library/nginx:stable-alpine-slim
      name: my-container
      env:
        - name: HELLO
          valueFrom:
            configMapKeyRef:
              name: my-config-map
              key: message1