apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
    - image: docker.io/library/nginx:stable-alpine-slim
      name: hello
      volumeMounts:
        - name: config
          mountPath: /etc/config
  volumes:
    - name: config
      configMap:
        name: hello