version: "3.9"

services:

  # Backend ###################################################################

  backend:
    container_name: fastapi-hello
    image: fastapi_hello:latest
    build: .
    # restart: always
    ports:
      - "80:80"
