FROM python:3.12-slim

RUN apt update --yes && \
    apt install --yes --no-install-recommends \
    libgl1 \
    libglib2.0-0 && \
    apt clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements-minimal.txt /app
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /app/requirements-minimal.txt
