positionAttitudeTransform : positionAttitudeTransform.cc
	gcc -Wall -o positionAttitudeTransform `pkg-config --libs openscenegraph` positionAttitudeTransform.cc

clean :
	rm positionAttitudeTransform
