apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
    - image: docker.io/library/nginx:stable-alpine-slim
      name: my-container
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
