// Configuration minimaliste pour bind9

options {
    directory "/var/cache/bind";

    // Ne pas utiliser les résolveurs du système hôte
    recursion no;

    // Écouter sur toutes les interfaces
    listen-on { any; };
    listen-on-v6 { none; };

    // Autoriser les requêtes de partout (test local)
    allow-query { any; };
};

// Logs
logging {
    channel default_log {
        stderr;
        severity dynamic;
        print-time yes;
    };
    category default { default_log; };
    category queries { default_log; };
};

// Zone pour les enregistrements statiques
zone "jdhp.org" {
    type master;
    file "/etc/bind/db.jdhp.org";
};
