#!/bin/sh

# Hello
# Copyright (c) 2012 Jérémie DECOCK <jd.jdhp@gmail.com>

ROOT="."
JVM_ARGS="$@"
PROGRAM_ARGS=
LIBS="${ROOT}/bin/"

#java ${JVM_ARGS} -jar ${ROOT}/hello_swing.jar ${PROGRAM_ARGS}
java ${JVM_ARGS} -cp ${LIBS} org.jdhp.snippets.swing.HelloSwing ${PROGRAM_ARGS}

