#!/bin/sh

# Hello
# Copyright (c) 2012 Jérémie DECOCK <jd.jdhp@gmail.com>

ROOT="."
OPTS=
LIBS="${ROOT}/bin/"

#java ${OPTS} $@ -jar ${ROOT}/hello_swing.jar
java ${OPTS} $@ -cp ${LIBS} org.jdhp.snippets.swing.HelloSwing
