apiVersion: v1
kind: Secret
metadata:
  name: ovh-mpr-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "<YOUR_REGISTRY_SUB_DOMAIN>.container-registry.ovh.net": {
          "username": "robot$<YOUR_ROBOT_ACCOUNT_NAME>",
          "password": "<YOUR_ROBOT_ACCOUNT_TOKEN>"
        }
      }
    }
