apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    application: flask-nginx
    component: flask
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    application: flask-nginx
    component: flask
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    application: flask-nginx
    component: flask
spec:
  replicas: 1
  progressDeadlineSeconds: 480
  selector:
    matchLabels:
      application: flask-nginx
      component: flask
  template:
    metadata:
      labels:
        application: flask-nginx
        component: flask
    spec:
      containers:
      - name: flask
        image: flask
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP