#!/bin/sh

OUTPUT_DEV_LIST=$(xrandr | grep -e " connected [^(]" | grep -v -e "^eDP" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/")

# Get connected outputs
for OUTPUT_DEV in ${OUTPUT_DEV_LIST}
do
    echo "Disable ${OUTPUT_DEV}"
    xrandr --auto && xrandr --output ${OUTPUT_DEV} --off
    #xrandr --auto && xrandr --output DP-1-3 --off
done
