#!/bin/sh

OUTPUT_DEV_LIST=$(xrandr | grep -e " connected (" | grep -v -e "^eDP" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/")

# Get connected outputs
for OUTPUT_DEV in ${OUTPUT_DEV_LIST}
do
    echo "Enable ${OUTPUT_DEV}"
    xrandr --output ${OUTPUT_DEV} --mode 1920x1080 --above eDP-1-1
    #xrandr --output DP-1-3 --mode 1920x1080 --above eDP-1-1
done
