FROM python:3.12-slim

# USER root

RUN apt update --yes && \
    apt install --yes --no-install-recommends \
    ffmpeg && \
    apt clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
