server:
    # Écouter sur toutes les interfaces
    interface: 0.0.0.0
    port: 53

    # Autoriser les requêtes de partout (test local)
    access-control: 0.0.0.0/0 allow

    # Pas de récursion vers des serveurs externes
    do-not-query-localhost: no

    # Désactiver DNSSEC (test minimaliste)
    module-config: "iterator"

    # Logs en foreground
    use-syslog: no
    logfile: ""
    verbosity: 2
    log-queries: yes

    # Désactiver IPv6
    do-ip6: no

    # Enregistrements DNS statiques
    local-zone: "jdhp.org." static

    local-data: "foo.jdhp.org. 60 IN A 192.168.0.1"
    local-data: "bar.jdhp.org. 60 IN A 192.168.0.2"
