apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - image: docker.io/your-username/hello-fastapi:3.0
          name: my-container
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: my-config-map
                  key: message
            - name: SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: token
