FROM python:3.12-slim

# Git is required to log git repositories in ClearML
RUN apt update -y && apt install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements-devcontainers.txt /app
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /app/requirements-devcontainers.txt
